language: objective-c
osx_image: xcode8
before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild -project Examples/DynamicColorExample.xcodeproj -scheme iOSTests -sdk iphonesimulator -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
  - xcodebuild -project Examples/DynamicColorExample.xcodeproj -scheme OSXTests -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
